import torch

MAX_EPISODE_LEN = 100
MAX_RACK_NUM = 2

MAX_SRV_NUM_IN_SINGLE_RACK = 5
MAX_SRV_NUM = MAX_SRV_NUM_IN_SINGLE_RACK * MAX_RACK_NUM
MAX_SRV_VCPU_NUM = 500
MAX_SRV_VMEM_MB = 1024 * 1024  # 1 TB

MAX_SFC_NUM = 30

MAX_VNF_NUM = 30
MAX_VNF_VCPU_NUM = 500
MAX_VNF_VMEM_MB = 1024 * 1024  # 10 TB

TORCH_DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

EPS = 1e-6